name: Generated AAR File

env:
  # The name of the main module repository
  module_name: sean

on:

  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - shell: bash
        env:
          GPG: ${{ secrets.GPG_FILE }}
          GPG_KEY_ID: ${{ secrets.GPG_ID_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: |
          echo $GPG | base64 --decode > ./sean/secring.gpg
          echo -e "\nsigning.keyId=$GPG_KEY_ID\nsigning.password=$GPG_PASSWORD\nsigning.secretKeyRingFile=secring.gpg\n" >> gradle.properties


      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build library
        run: ./gradlew sean:publishAllPublicationsToMavenRepository

      - shell: bash
        env:
          BEARER: ${{ secrets.MAVEN_CENTRAL }}
        run: |
          cd ./sean/build/repos/releases
          zip -r io.zip io/
          curl -X 'POST' \
            'https://central.sonatype.com/api/v1/publisher/upload?name=1.0.1&publishingType=USER_MANAGED' \
            -H 'accept: text/plain' \
            -H "Authorization: Bearer $BEARER" \
            -H 'Content-Type: multipart/form-data' \
            -F 'bundle=@io.zip;type=application/zip'

      - name: Upload AAR
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - lib - ${{ env.repository_name }} - AAR(s)  generated
          path: ${{ env.module_name }}/build/repos/releases/
