name: Publish to maven

env:
  # The name of the main module repository
  module_name: sean

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: get zip
        run: echo "assume we do zip here"

      - name: upload
        env:
          bearer: ${{ secrets.CENTRAL_TOKEN }}
        run: |
          curl -X 'POST' \
              'https://central.sonatype.com/api/v1/publisher/upload?name=1.0.1&publishingType=USER_MANAGED' \
              -H 'accept: text/plain' \
              -H 'Authorization: Bearer $bearer' \
              -H 'Content-Type: multipart/form-data' \
              -F 'bundle=@io.zip;type=application/zip'

