name: Publish to maven

env:
  # The name of the main module repository
  module_name: sean

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: get zip
        run: echo "assume we do zip here"

      - shell: bash
        uses: actions/upload-artifact@v4
        env:
          BEARER: ${{ secrets.MAVEN_CENTRAL }}
          GPG: ${{ secrets.GPG_FILE }}
          GPG_KEY_ID: ${{ secrets.GPG_ID_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
        run: |
          echo $GPG | base64 --decode > secring.gpg
          echo "\nsigning.keyId=$GPG_KEY_ID\nsigning.password=$GPG_PASSWORD\nsigning.secretKeyRingFile=secring.gpg\n" >> gradle.properties

      - name: Upload FILE TEST
        uses: actions/upload-artifact@v4
        with:
          path: test.txt

#        curl -X 'POST' \
#          'https://central.sonatype.com/api/v1/publisher/upload?name=1.0.1&publishingType=USER_MANAGED' \
#          -H 'accept: text/plain' \
#          -H "Authorization: Bearer $BEARER" \
#          -H 'Content-Type: multipart/form-data' \
#          -F 'bundle=@io.zip;type=application/zip'

